config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get 'welcome' => 'welcome#index'

  resources :policies

  resources :policy_templates

  get 'lti/launch'

  post 'lti/launch'

  get 'lti/error'

  get 'lti/index'

  get 'lti' => 'lti#index'

  get 'lti/configuration'

  get 'lti/config' => 'lti#configuration'

  get 'lti/config/ssl' => 'lti#configuration', :theProtocol => 'https://'

  root 'lti#index'

end

app/controllers/lti_controller.rb
# Need to require this expicitly in order to create the request proxy object 
# required for the LTI library.
require 'oauth/request_proxy/rack_request'

#
#
#
class LtiController < ApplicationController
  
  # The following allows us to send a POST request to this controller
  # without Rails's verification key.
  skip_before_filter  :verify_authenticity_token
  
  # Skips the need for an LTI launch for several of this controller's
  # actions. The function 'require_lti_launch' is defined in 
  # ApplicationController.rb.
  skip_before_action :require_lti_launch

  # This is controller for the main page of the application, returned
  # when a user goes to:
  #
  #     http://server:port/
  #
  # The page informs the user that this is an LTI application, and 
  # requires LTI authentication. This is also the root route of the 
  # application.
  def index
  end

  # Produces the XML configuration file needed to add the tool
  # to Canvas. Returned when a user goes to:
  #    
  #     http://server:port/configuration
  #     http://server:port/config
  #     http://server:port/config/ssl
  #
  def configuration
    @host = request.host
    @port = request.port

    # Set the protocol to either 'http://' or what has been
    # defined in ':protocol' for the routes.rb file.
    @theProtocol = params[:theProtocol] ? params[:theProtocol] : "http://"

    # Hmmm. Have to explicitly declare this to render the .xml
    # file, which doesn't make too much sense to me. 
    render "lti/configuration.xml.erb"

  end


  # Attempts to launch the LTI request. If successful, then go to the
  # main page of the application at http://server:port/policy/
  #
  # This page is returned by the following URL:
  #     http://server:port/lti/launch
  #
  def launch
    isLTILaunch = true;
    errMsg      = "An LTI error occurred."

    # Grab our oauth consumer key and secret
    oauth_secret       = Global.oauth.oauth_secret
    oauth_consumer_key = params[:oauth_consumer_key]
    logger.debug "Oauth secret: '#{oauth_secret}'"

    # Create new request to apply to the ToolProvider object.
    req  = OAuth::RequestProxy::RackRequest.new request
    provider = IMS::LTI::ToolProvider.new oauth_consumer_key, oauth_secret, params


    # Send ToolProvider the request for an LTI launch. If the LTI
    # launch is invalid, generate an error message. This can probably
    # be written much better.
    begin
      if !provider.valid_request? req, false
        
      end
    rescue Exception => e
      isLTILaunch = false
      errMsg = e.message
    end
    
    # Determine if the LTI launch is valid or not. 
    # If not, then render the error page with a message.
    if !isLTILaunch
      flash.now[:alert] = "Invalid LTI launch: '#{errMsg}'"
      render 'error'
      else

      # We had a successful LTI launch. Wrap up some of the post
      # parameters in a session variable. 
      # session[:context_id] = context_id = params[:context_id]
      # session[:course_id]  = course_id  = params[:custom_canvas_course_id]
      session[:context_id] = context_id = params[:custom_canvas_course_id]
      session[:uid]        = params[:custom_canvas_user_login_id]

      # Mike's lame attempt at security
      session[:lti_launch] = true

      # Determine if we are an instuctor, TA, or designer
      if provider.instructor? || provider.ta? || provider.content_developer?
        session[:is_admin] = true
      else
        session[:is_admin] = false
      end

      # Uncomment the below line to test if we are a student.
      # session[:is_admin] = false;

      # Find the policy associated with this context_id
      @policy = Policy.find_by :context_id => context_id

      # If no policy, then go to the index page for policies.
      #     http://server:port/policies/
      # 
      # Otherwise, go to the show page for the policies.
      #     http://server:port/policies/show/[:id]
      #
      if @policy
        redirect_to @policy
      else
        redirect_to policies_url
      end
    end

    end

    # Renders a page with an error in it.
    #   http://server:port/lti/error
    def error
    end

end

app/helpers/lti_helper.rb
module LtiHelper
end

app/views/lti/configuration.xml.erb
<cartridge_basiclti_link xsi:schemalocation="http://www.imsglobal.org/xsd/imslticc_v1p0 http://www.imsglobal.org/xsd/lti/ltiv1p0/imslticc_v1p0.xsd http://www.imsglobal.org/xsd/imsbasiclti_v1p0 http://www.imsglobal.org/xsd/lti/ltiv1p0/imsbasiclti_v1p0p1.xsd http://www.imsglobal.org/xsd/imslticm_v1p0 http://www.imsglobal.org/xsd/lti/ltiv1p0/imslticm_v1p0.xsd http://www.imsglobal.org/xsd/imslticp_v1p0 http://www.imsglobal.org/xsd/lti/ltiv1p0/imslticp_v1p0.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:lticp="http://www.imsglobal.org/xsd/imslticp_v1p0"
  xmlns:lticm="http://www.imsglobal.org/xsd/imslticm_v1p0"
  xmlns:blti="http://www.imsglobal.org/xsd/imsbasiclti_v1p0"
  xmlns="http://www.imsglobal.org/xsd/imslticc_v1p0">
  <blti:title>Academic Integrity Policy Tool</blti:title>
  <blti:description>
    <!--[CDATA[The Academic Integrity Policy Tool allows course instructors to easily choose and display an academic policy for collaboration.]]-->
  </blti:description>
  <blti:launch_url><%= @theProtocol %><%= @host %>:<%= @port %>/lti/launch</blti:launch_url>
  <blti:icon><%= @theProtocol %><%= @host %>:<%= @port %>/images/integrity.png</blti:icon>
  <blti:custom></blti:custom>
  <blti:extensions platform="canvas.instructure.com">
    <lticm:property name="tool_id">academic_integrity_tool</lticm:property>
    <lticm:property name="icon_url"><%= @theProtocol %><%= @host %>:<%= @port %>/images/integrity.png</lticm:property>
    <lticm:property name="domain"><%= @host %></lticm:property>
    <lticm:property name="privacy_level">public</lticm:property>
    <lticm:property name="text">Academic Integrity Policy</lticm:property>
    <lticm:options name="course_navigation">
      <lticm:property name="enabled">true</lticm:property>
      <lticm:property name="url"><%= @theProtocol %><%= @host %>:<%= @port %>/lti/launch</lticm:property>
      <lticm:property name="visibility">public</lticm:property>
    </lticm:options>
  </blti:extensions>
</cartridge_basiclti_link>

app/views/lti/error.html.erb
<h2>Sorry, but we encountered a problem.</h2>
<p>
	We are unable to continue because of the following issue:
</p>	
<p>
	<%= flash[:alert] %>
</p>

app/views/lti/index.html.erb
<h1>Academic Policy Wizard</h1>
<p>
	Welcome to the new version of the Academic Integrity Policy Tool, which is fully compatible with the Learning Tools Interoperability (LTI) specification, though designed to be installed with <%= link_to "Canvas By Instructure", "http://www.instructure.com/" %>.
</p>

<p>
	To install as an app in Canvas:
	<ol>
		<li>
			<strong>If you are running this application on a basic http server</strong>, you will need the <%= link_to "XML configuration file for the http protocol", lti_config_url %>.
		</li>
		<li>
			<strong>If you are running this application on an SSL server</strong>, you will need the <%= link_to "XML configuration file for the https protocol", lti_config_ssl_url %>.
		</li>
	</ol>			
</p> 

app/views/lti/launch.html.erb
<h1>Lti#launch</h1>
<p>Find me in app/views/lti/launch.html.erb</p>