config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get 'welcome' => 'welcome#index'

  resources :policies

  resources :policy_templates

  get 'lti/launch'

  post 'lti/launch'

  get 'lti/error'

  get 'lti/index'

  get 'lti' => 'lti#index'

  get 'lti/configuration'

  get 'lti/config' => 'lti#configuration'

  get 'lti/config/ssl' => 'lti#configuration', :theProtocol => 'https://'

  root 'lti#index'

end

app/models/policy_template.rb
class PolicyTemplate < ActiveRecord::Base
end

app/controllers/policy_templates_controller.rb
class PolicyTemplatesController < ApplicationController
  before_action :set_policy_template, only: [:show, :edit, :update, :destroy]

  # Uncomment to skip the need for an LTI launch for these
  # requests. The function 'require_lti_launch' is defined in 
  # ApplicationController.rb.
  # skip_before_action :require_lti_launch
  
  # Standard Rails page that lists all policy templates.
  #
  # GET /policy_templates
  # GET /policy_templates.json
  def index
    @policy_templates = PolicyTemplate.all
  end

  # Standard Rails page that shows an individual policy
  # template.
  #
  # GET /policy_templates/1
  # GET /policy_templates/1.json
  def show
  end

  # Standard Rails request that shows an edit page.
  # GET /policy_templates/new
  #
  def new
    @policy_template = PolicyTemplate.new
  end

  # Standard Rails request that shows an edit screen.
  # GET /policy_templates/1/edit
  #
  def edit
  end

  # Default Rails procedure that generates a new policy template.
  #
  # POST /policy_templates
  # POST /policy_templates.json
  def create
    @policy_template = PolicyTemplate.new(policy_template_params)

    respond_to do |format|
      if @policy_template.save
        format.html { redirect_to @policy_template, notice: 'Policy template was successfully created.' }
        format.json { render :show, status: :created, location: @policy_template }
      else
        format.html { render :new }
        format.json { render json: @policy_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # Default Rails procedure for updating a policy template.
  #
  # PATCH/PUT /policy_templates/1
  # PATCH/PUT /policy_templates/1.json
  #
  def update
    respond_to do |format|
      if @policy_template.update(policy_template_params)
        format.html { redirect_to @policy_template, notice: 'Policy template was successfully updated.' }
        format.json { render :show, status: :ok, location: @policy_template }
      else
        format.html { render :edit }
        format.json { render json: @policy_template.errors, status: :unprocessable_entity }
      end
    end
  end

  
  # Default Rails procedure for deleting a policy template.
  #
  # DELETE /policy_templates/1
  # DELETE /policy_templates/1.json
  def destroy
    @policy_template.destroy
    respond_to do |format|
      format.html { redirect_to policy_templates_url, notice: 'Policy template was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_policy_template
      @policy_template = PolicyTemplate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def policy_template_params
      params.require(:policy_template).permit(:name, :is_active, :body)
    end
end

app/helpers/policy_templates_helper.rb
module PolicyTemplatesHelper
end

app/views/policy_templates/_form.html.erb
<%= form_for(@policy_template) do |f| %>
  <% if @policy_template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@policy_template.errors.count, "error") %> prohibited this policy_template from being saved:</h2>

      <ul>
      <% @policy_template.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :is_active %><br>
    <%= f.check_box :is_active %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/policy_templates/edit.html.erb
<h1>Editing policy_template</h1>

<%= render 'form' %>

<%= link_to 'Show', @policy_template %> |
<%= link_to 'Back', policy_templates_path %>

app/views/policy_templates/index.html.erb
<h1>Listing policy_templates</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Is active</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @policy_templates.each do |policy_template| %>
      <tr>
        <td><%= policy_template.name %></td>
        <td><%= policy_template.is_active %></td>
        <td><%= policy_template.body %></td>
        <td><%= link_to 'Show', policy_template %></td>
        <td><%= link_to 'Edit', edit_policy_template_path(policy_template) %></td>
        <td><%= link_to 'Destroy', policy_template, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Policy template', new_policy_template_path %>

app/views/policy_templates/new.html.erb
<h1>New policy_template</h1>

<%= render 'form' %>

<%= link_to 'Back', policy_templates_path %>

app/views/policy_templates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @policy_template.name %>
</p>

<p>
  <strong>Is active:</strong>
  <%= @policy_template.is_active %>
</p>

<p>
  <strong>Body:</strong>
  <%= @policy_template.body %>
</p>

<%= link_to 'Edit', edit_policy_template_path(@policy_template) %> |
<%= link_to 'Back', policy_templates_path %>