config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get 'welcome' => 'welcome#index'

  resources :policies

  resources :policy_templates

  get 'lti/launch'

  post 'lti/launch'

  get 'lti/error'

  get 'lti/index'

  get 'lti' => 'lti#index'

  get 'lti/configuration'

  get 'lti/config' => 'lti#configuration'

  get 'lti/config/ssl' => 'lti#configuration', :theProtocol => 'https://'

  root 'lti#index'

end

app/models/policy.rb
class Policy < ActiveRecord::Base
	validates :body, :presence => true
end

app/controllers/policies_controller.rb
class PoliciesController < ApplicationController
 
  # TOODO: We should probably add a before_action that checks to 
  # determine if the user is an admin or not. Will add security.
  before_action :set_policy, only: [:show, :edit, :update, :destroy]

  
  # Shows the main page of the Academic Policy Wizard depending
  # on whether the user is an admin or a student.
  #
  # * If the user is an admin and no policy has been created,
  #   show the three templates to the admin.
  # * If the user is an admin and a policy has been created,
  #   show the edit screen to the admin.
  # * If the user is a student and a policy has not been 
  #   created/published, then show a message stating that 
  #   there is no policy. 
  # * If the user is a student and a policy has been
  #   created/published, display the policy.
  #
  # GET /policies
  # GET /policies.json
  def index

    # Attempt to find a policy for this context id. If one can
    # be found, show it. Otherwise, get the three policy
    # templates and display those along with instructions.
    @context_id = session[:context_id]
    @is_admin   = session[:is_admin]
    @policy = Policy.find_by :context_id => @context_id


    # If the user is an admin, then show the edit screen.
    if @policy && @is_admin
      render 'edit'

    else
      # Find the three policy templates, then render the form.
      @policy_01 = PolicyTemplate.find_by :id => 1
      @policy_02 = PolicyTemplate.find_by :id => 2
      @policy_03 = PolicyTemplate.find_by :id => 3
    end
  end

  # Shows an individual policy, but only if it is published.
  # GET /policies/1
  # GET /policies/1.json
  def show
    @is_admin = session[:is_admin]

    # Do not show policy if user is not an admin and the policy is not published.
    # In other words, students can't see unpublished policies.
    if !@is_admin && !@policy.is_published
      redirect_to policies_url
      return
    end
  end

  # Shows the 'new policy' screen to administrators, which may
  # include a chosen policy template.
  #
  # GET /policies/new
  def new

    # Create a new Policy object.
    @policy = Policy.new


    # If a template has been choosen, then grab the template and
    # set the body of the Policy object to the text of the template.
    if params[:custom]
      @policy_template = PolicyTemplate.find_by :id => params[:custom]
      @policy.body = @policy_template.body
    end
    # Render the form
  end

  # Default Rails procedure for displaying an 'edit policy' screen.
  # GET /policies/1/edit
  def edit
  end

  # Default Rails procedure for creating a new policy (unless)
  # a cancel button has been pressed. 
  #
  # POST /policies
  # POST /policies.json
  def create
    # If the cancel button is pressed, redirect back to the index page
    # of the policies controller. 
    #
    # @@Note: Should this be handled in the form link itself? 
    if params[:cancel] 
      redirect_to policies_url
      return
    end

    # Create a Policy object and set some standard data.
    @policy              = Policy.new
    @policy.body         = params[:policy][:body]
    @policy.published_by = session[:uid]
    @policy.context_id   = session[:context_id]

    # Determine if Policy is being published or not.
    if params[:publish]
      @policy.is_published = true
    else
      @policy.is_published = false;
    end

    # Determin if this is a custom policy, which really
    # doesn't make sense if we think about, because if no
    # custom parameter is passed, it becomes a template??
    #
    # @@NOTE: Horrible, horrible code logic. Redo.
    if params[:custom]
      @policy.policy_template_id = params[:custom]
    else 
      @policy.policy_template_id = 0
    end

    respond_to do |format|
      if @policy.save
        format.html { redirect_to @policy, notice: 'Policy was successfully created.' }
        format.json { render :show, status: :created, location: @policy }
      else
        format.html { render :new }
        format.json { render json: @policy.errors, status: :unprocessable_entity }
      end
    end
  end

  # Default Rails procedure for updating a policy (unless)
  # a cancel button has been pressed. 
  #
  # PATCH/PUT /policies/1
  # PATCH/PUT /policies/1.json
  def update
    # If the cancel button is pressed, redirect back to the index page
    # of the policies controller
    #
    # @@NOTE: Add to form, as opposed to in this log?
    if params[:cancel] 
      redirect_to @policy
      return
    end

    # Determine if we are publishing the policy.
    if params[:publish]
      @policy.is_published = true
    else
      @policy.is_published = false;
    end

    respond_to do |format|
      if @policy.update(policy_params)
        format.html { redirect_to @policy, notice: 'Policy was successfully updated.' }
        format.json { render :show, status: :ok, location: @policy }
      else
        format.html { render :edit }
        format.json { render json: @policy.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # Default Rails procedure for removing a policy. 
  #
  # DELETE /policies/1
  # DELETE /policies/1.json
  def destroy
    @policy.destroy
    respond_to do |format|
      format.html { redirect_to policies_url, notice: 'Policy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_policy
      @policy = Policy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def policy_params
      params.require(:policy).permit(:context_id, :policy_template_id, :is_published, :published_by, :body)
    end
end

app/helpers/policies_helper.rb
module PoliciesHelper
end

app/views/policies/_form.html.erb
<% content_for :tinymce do %>
<% end %> 

<%= form_for(@policy) do |f| %>
  <% if @policy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@policy.errors.count, "error") %> prohibited this policy from being saved:</h2>

      <ul>
      <% @policy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :body, :size => '100x20', :id => 'myEditor' %>
  </div>
  <% if params[:custom] %>
    <%= hidden_field_tag "custom", params[:custom] %>
  <% end %>
  <div class="actions">
    <%= f.submit "Publish", :name => "publish" %> 
    <% if !@policy.is_published? %>
      <%= f.submit "Save As Draft", :name => "draft" %> 
    <% end %>
    <%= f.submit "Cancel", :name => "cancel" %>
  </div>
<% end %>

  <script type="text/javascript">
    $(document).ready(function() {
      tinymce.init({
        selector: "#myEditor",
        menubar: false,
        toolbar: "bold italic | bullist numlist outdent indent",
        relative_urls: true,
        document_base_url: "/js/tinymce/",
      });
    });
  </script>

app/views/policies/edit.html.erb
<h2>Editing policy</h2>

<%= render 'form' %>

app/views/policies/index.html.erb
<% if !@is_admin %>
  <h2>No policy has been created yet.</h2>
<% else %>

  <h2>Instructions for the Faculty</h2>

  <div class="highlighted">
    <p>
      As stated in <a href="http://infoforfaculty.fas.harvard.edu/" target="_new" title="Information for Faculty">Information for Faculty</a>: “It is essential that instructors set out carefully in writing and at the outset of a course or course assignment the extent of permissible student collaboration in the preparation of papers, computer programs, or examinations. <strong>Students must assume that collaboration in the completion of assignments is permitted unless explicitly prohibited by the instructor.</strong> Students should be reminded that they are expected to acknowledge any collaboration and its extent in all submitted work.”
    </p>
    <p>
      Reviewing the <a href="http://honor.fas.harvard.edu/" target="_new">the Honor Code website</a> may be of assistance as you determine your policy, particularly the sections on the <a href="http://honor.fas.harvard.edu/affirmation" target="_new">Affirmation</a> and <a href="http://honor.fas.harvard.edu/teaching-integrity" target="_new">Teaching With Integrity.</a>
    
    <p>
      Please select the relevant description below, or you may customize your policy on collaboration for this class. 
    </p>
  </div>

  <h2>I. Collaboration Permitted</h2>

  <h3>a. Written Work</h3>
  <p class="highlighted">
    <%= @policy_01.body %> 
  </p>
  <%= form_tag new_policy_url, :method => "get" do %>
    <%= hidden_field_tag "custom", @policy_01.id %>
    <%= submit_tag "Choose This Template" %>
  <% end %>

  <h3>b. Problem Sets</h3>
  <p class="highlighted">
    <%= @policy_02.body %>
  </p>
  <%= form_tag new_policy_url, :method => "get" do %>
    <%= hidden_field_tag "custom", @policy_02.id %>
    <%= submit_tag "Choose This Template" %>
  <% end %>

  <h2>II. Collaboration Prohibited</h2>
  <p>
    <%= @policy_03.body %> 
  </p>
  <%= form_tag new_policy_url, :method => "get" do %>
    <%= hidden_field_tag "custom", @policy_03.id %>
    <%= submit_tag "Choose This Template" %>
  <% end %>

  <h2>III. Instructions For Customizing Collaboration Policy</h2>
  <p>
    If you choose to write your own policy on collaboration, keep the following guidelines in mind.
  </p>

  <ol>
      <li>
        You should outline explicitly what students may or may not discuss with their classmates outside the classroom and how best to capture those discussions on formal work submitted for course credit.
      </li>
      <li>
        You may want to include citation resources for students including the <a href="http://usingsources.fas.harvard.edu/" title="Harvard Guide to Using Sources">Harvard Guide to Using Sources</a>.
      </li>
      <li>
        You may want to include information about conforming to the College’s policies on academic integrity found in the <a href="http://handbook.fas.harvard.edu/" title="Harvard College Handbook for Students">Harvard College Handbook for Students</a>.
      </li>
  </ol>

  <%= form_tag new_policy_url, :method => "get" do %>
    <%= submit_tag "Create A Custom Policy" %>
  <% end %>
<% end %>

app/views/policies/new.html.erb
<h2>New policy</h2>

<%= render 'form' %>

app/views/policies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= sanitize @policy.body, :tags => %w(p b strong em i ul ol li), :attributes => %w(style) %>
</p>

<% if @is_admin %>
  <% if !@policy.is_published? %>
    <p>
      <strong>Note:</strong> This policy has not been published, and is not being displayed to students. To publish it, you must first <%= link_to 'edit this policy', edit_policy_path(@policy) %>, then click the &quot;Publish&quot; button.
    </p>
  <% else %>
    <p>
      As an instructor, you may <%= link_to 'edit this policy', edit_policy_path(@policy) %>.
    </p>
  <% end %>
<% end %>